# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements_dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            pyenv update
            pyenv install 3.5.4
            pyenv install 3.6.3
            pyenv global 3.6.3 3.5.4
            pip install tox
            tox -vv --notest

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements_dev.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            eval "$(pyenv init -)"
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports